name: Deploy Innovatech EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Mensaje de prueba
        run: |
          echo "Pipeline ejecutado correctamente"
          echo "Proyecto Innovatech EP3 - EKS"o

